### ISSUE TITLE
TODO - 0.0.1b1

### ISSUE THREAD

**Issue by delarosatrevin** [3dem/emhub#29]
### TODO List

* [x] Make Welcome page the default index one
* [x] Visibility:  hide Create Applications (it is not possible now)
* [x] Show only last X logs entries (also inverted from more recent)
* [x] Show/Edit Application (CEM code/alias) in  the Booking  form
* [x] Compulsory  (or more visible) to open  "Describe your Experiment"
